examples = [
    ("Are there any nearby cafés suitable for relaxing alone?", "Monera"),
    ("Is there a quiet tea house where I can sit alone?", "Monera"),
    ("Are there any nearby SPA places good for solo visits?", "Monera"),
    ("I'm looking for a comfy café to zone out alone—any recommendations?", "Monera"),
    ("Any artsy places nearby where I can enjoy tea alone?", "Monera"),
    ("Where can I find a quiet and affordable SPA for solo experience?", "Monera"),
    ("Any place you'd recommend for slowly sipping coffee and reading alone?", "Monera"),
    ("Are there any tea houses where going alone doesn’t feel awkward?", "Monera"),
    ("Looking for a light luxury SPA suitable for solo time—any nearby?", "Monera"),
    ("Any recommended coffee shops good for being alone?", "Monera"),
    ("Any coffee shops nearby that are good for studying alone?", "Susan"),
    ("Any recommended spots for a small gathering with friends?", "Jan"),
    ("I want something special—any local restaurant recommendations?", "Brian"),
    ("Where can I relax alone by visiting an art exhibition?", "Leonel"),
    ("Looking for a quiet place to work—any suggestions?", "Eiman"),
    ("Any bars with good nighttime vibes for zoning out alone?", "Harry"),
    ("Any artsy cafés that are good for photo ops?", "Jimmy"),
    ("Any good SPAs or body treatments you'd recommend nearby?", "Shaiqiyah"),
    ("Any tea house where I can enjoy tea and write my diary alone?", "Russell"),
    ("Any spots suitable for meditation or breathing exercises?", "Talia"),
    ("Where can I spend a whole day reading alone on the weekend?", "Ted"),
    ("Any places to quietly listen to music, like a book café?", "Candace"),
    ("Which dessert shop has great taste and ambiance for relaxing?", "Madeleine"),
    ("Any romantic restaurants where going alone still feels comfortable?", "Chantelle"),
    ("I want to experience a luxury SPA in the city—any suggestions?", "David"),
    ("Any quiet coworking spaces that are good for working?", "Daniel"),
    ("Any niche exhibitions or events worth checking out this weekend?", "Andrew"),
    ("Any place good for a solo walk by the sea?", "Keny"),
    ("Looking for a small, beautiful spot in the city to spend an afternoon—any ideas?", "Claire"),
    ("Any cozy and artsy afternoon tea spots nearby?", "Michelle"),
    ("Feeling stressed lately—any suggestions for places to relax?", "Elizabeth"),
    ("Any restaurants good for enjoying a solo dinner comfortably?", "Jacque"),
]




