examples = [
    ('Looking for a sushi restaurant downtown.', 'Jimmy'),
    ('I need a gym with personal trainers nearby.', 'Monera'),
    ('Can you find a pet store that sells organic food?', 'Elizabeth'),
    ('I want to get a haircut and maybe some styling done.', 'Jacque'),
    ('Need someone to fix my car’s engine and check the tires.', 'David'),
    ('Planning to relax with a massage this weekend.', 'Michelle'),
    ('Searching for a coffee shop or bakery open late.', 'Brian'),
    ('I have to visit the dentist and also get a facial.', 'Keny'),
    ('Looking for something fun to do with kids this Saturday.', 'Leonel'),
    ('I’m craving some food before catching a movie.', 'Russell'),
    ('Just wandering around, no specific plans.', 'Talia'),
    ('Not sure what I want, just exploring options.', 'Susan'),
    ('Need a daycare center that accepts infants.', 'Chantelle'),
    ('Looking for a 24-hour pharmacy nearby.', 'Andrew'),
    ('Want to find a place to learn painting classes.', 'Harry'),
    ("附近有没有适合一人放松的咖啡馆？", "Monera"),
    ("有什么安静的茶馆适合一个人坐坐？", "Monera"),
    ("周围有没有适合独自去的SPA店？", "Monera"),
    ("想找个环境舒服的咖啡馆，一个人发呆用，有推荐吗？", "Monera"),
    ("附近有没有文艺一点、适合一个人喝茶的地方？", "Monera"),
    ("哪里有安静又不贵的SPA可以一个人去体验？", "Monera"),
    ("适合一人慢慢喝咖啡、看看书的地方有没有推荐？", "Monera"),
    ("有没有那种一个人去也不会尴尬的茶馆？", "Monera"),
    ("想找家适合一个人去的轻奢SPA，附近有吗？", "Monera"),
    ("有没有推荐适合独处的咖啡店？", "Monera"),
    ("附近有没有适合一个人学习的咖啡店？", "Susan"),
    ("有没有推荐的地方可以和朋友小聚一下？", "Jan"),
    ("想吃点特别的，有没有本地人推荐的餐馆？", "Brian"),
    ("适合一个人看展放松的地方有哪些？", "Leonel"),
    ("我想找个环境安静、适合办公的地方，有推荐吗？", "Eiman"),
    ("有什么夜晚氛围好的酒吧，适合一个人放空？", "Harry"),
    ("有没有地方适合拍照打卡的文艺咖啡馆？", "Jimmy"),
    ("附近有没有做得不错的SPA或身体护理推荐？", "Shaiqiyah"),
    ("有没有适合一人慢慢品茶、写写日记的茶馆？", "Russell"),
    ("想找个适合冥想或呼吸练习的场所，有吗？", "Talia"),
    ("周末适合带书一个人坐一天的地方有哪些？", "Ted"),
    ("有没有推荐可以静静听音乐的书吧或店？", "Candace"),
    ("哪家甜品店的环境和味道都不错，适合放松？", "Madeleine"),
    ("有没有那种氛围浪漫但一个人去也自在的餐厅？", "Chantelle"),
    ("我想体验一次城市里的轻奢SPA，有建议吗？", "David"),
    ("有没有不太吵、适合工作的共享空间？", "Daniel"),
    ("周末有没有什么小众展览或活动值得一去？", "Andrew"),
    ("有没有适合一人看海、走走的地方？", "Keny"),
    ("想在城市里找个小而美的地方待一下午，有推荐吗？", "Claire"),
    ("附近有没有文艺又温馨的下午茶店？", "Michelle"),
    ("最近压力大，想找个地方放松下，有什么建议？", "Elizabeth"),
    ("想独自一人享受一顿晚餐，有哪家餐厅比较舒服？", "Jacque"),
]




